apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-webapp
spec:
  replicas: 3
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      labels:
        app: webapp
    spec:
      containers:
      - name: webapp
        image: m8ndevops/flask:latest
---
kind: Service
apiVersion: v1
metadata:
  name: service-webapp
spec:
  ports:
    - name: http
      port: 8080
      targetPort: 8080
  selector:
    app: webapp
  type: NodePort
